### ISSUE TITLE
Morning Session (Code Review Suggestions)

### ISSUE THREAD

**Issue by Mosams** [youmari/portfolio#8]
# Project Highlights

- Amazing attention and replication of the figma template
- Working links on the media icons to respective platforms 🔥 
- No linters errors and proper Github flow

# Suggestions for improvement

- Suggesting the addition of the desktop version screenshot in the readme file.
- Re-adjusting the hamburger button for better visibility (The background image affects it)

**Comment by youmari** [comment]
All Done thanks for your review
